version: '3'

volumes:
  pg_data_pro:
  static:
  media:

services:
  db:
    image: postgres:13.10
    restart: always
    env_file: .env
    volumes:
      - pg_data_pro:/var/lib/postgresql/data

  backend:
    image: anxiaolong1103/kittygram_backend
    restart: always
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - db

  frontend:
    env_file: .env
    image: anxiaolong1103/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
    depends_on:
      - backend
    
  gateway:
    image: anxiaolong1103/kittygram_gateway
    restart: always
    env_file: .env
    volumes:
      - static:/static
      - media:/media
    ports:
      - 9000:80
    depends_on:
      - frontend