version: '3'

volumes:
  pg_data_production:
  static:
  media:

services:
  db_kittygram:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: anxiaolong1103/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - db_kittygram
  frontend:
    image: anxiaolong1103/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: anxiaolong1103/kittygram_gateway
    env_file: .env
    volumes:
      - static:/staticfiles
      - media:/media
    ports:
      - 9000:80
